steps:
  # Step 1: Build the container image using Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:latest'
      # Build-time environment variables (Required for Next.js NEXT_PUBLIC_* vars)
      - '--env=NEXT_PUBLIC_MESSENGER_URL=$_NEXT_PUBLIC_MESSENGER_URL'
      - '--env=NEXT_PUBLIC_GA4=$_NEXT_PUBLIC_GA4'
      - '--env=NEXT_PUBLIC_ADS_ID=$_NEXT_PUBLIC_ADS_ID'
      - '--env=NEXT_PUBLIC_CHATKIT_PUBLIC_KEY=$_NEXT_PUBLIC_CHATKIT_PUBLIC_KEY'
    id: Build

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID'
      # Non-secret runtime variables from Airtable/Google configuration
      - '--set-env-vars'
      - 'AIRTABLE_BASE_ID=appeJqZ5yjyPmh1MC,AIRTABLE_PARTICIPANTS_TABLE=Participants,GOOGLE_CALENDAR_ID=c_0cdca889ecc9974ca3f729265f27a3f951ff54e5844877d38681fe529e5e356b@group.calendar.google.com,GOOGLE_CLIENT_EMAIL=199373649190-compute@developer.gserviceaccount.com'
      # Secrets from Secret Manager
      - '--set-secrets'
      - 'AIRTABLE_API_KEY=AIRTABLE_API_K:latest,GOOGLE_PRIVATE_KEY=GOOGLE_PRIVATE_KEY:latest,MAKE_Mastermind_Registration_webhook_URL=_Registration_webhook_URL:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest'
    id: Deploy

images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

substitutions:
  _DEPLOY_REGION: us-east1
  _AR_HOSTNAME: us-east1-docker.pkg.dev
  _NEXT_PUBLIC_MESSENGER_URL: https://m.me/611741395360453
  _NEXT_PUBLIC_GA4: G-XXXXXXX
  _NEXT_PUBLIC_ADS_ID: AW-XXXXXXX
  _NEXT_PUBLIC_CHATKIT_PUBLIC_KEY: domain_pk_698d17e946248197841851887e60f432027a30b7008160cd

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
